### ISSUE TITLE
Working around CORS

### ISSUE THREAD

**Issue by nullset** [IBM/browser-functions#8]
Hi, in the docs it mentions that browser-functions can 

> work around CORS restrictions, i.e. proxy clients through the server

however I've not been able to make this work successfully, except on a non-cors protected endpoint (which a user's standard web browser could do anyway). Would you be able to provide a simple example of its usage?
Thanks!

**Comment by tobykurien** [comment]
Hi @nullset , because we are using a web browser on the backend, it is still subject to CORS restrictions. However, you can limit allowed CORS origins on the endpoint to just the app domain for your browser function. 

As an example, let's say you want to persist data to a CouchDb backend (as in this example: https://github.com/IBM/browser-functions/blob/master/functions_root/examples/files/storage/hitcounter.js ), then instead of setting CouchDb CORS to allow all origins, you could limit it to just the app domain, e.g.  `examples.browserfunctions.com`.

**Comment by nullset** [comment]
Ah I understand. Thanks for the clarification!
